server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-serve
  cloud:
    config:
      server:
        native:
          search-locations: file:src/main/resources/configurations